### PR TITLE
Add current cash and edit tp/sl rates

### PR DESCRIPTION
**Pull request by WarlaxZ**
Noticed this other guy has done a bunch of work to add the ability to update a position, get the cash available on account, and done some work around tp/sl - think it would be good to put into the repo

### CODE REVIEW

**Comment by WarlaxZ** [comment]
Sorry as a non repo owner for either I can't fix those conflicts for you, but if u want me to can fork and fix if u like?

**Comment by ok24601** [comment]
hi, you can resolve those in branch and make pool request than, and i'll merge it into master

**Comment by ok24601** [comment]
ah sorry, just noticed, it's a PR ;)

**Comment by ok24601** [comment]
i'm getting a lot of questions about this project these days

**Comment by ok24601** [comment]
it's merged now

**Pull request merged**
